/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sesion3.pkg1;

/**
 *
 * @author Cist
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CostoComputadora = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cImpresora = new javax.swing.JCheckBox();
        cScanner = new javax.swing.JCheckBox();
        cEstabilizador = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        credito = new javax.swing.JRadioButton();
        contado = new javax.swing.JRadioButton();
        seis = new javax.swing.JRadioButton();
        doce = new javax.swing.JRadioButton();
        dieciocho = new javax.swing.JRadioButton();
        Calcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CostoTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ImpuestoIGV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PrecioPagar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        MontoCuota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Costo de Computadora: ");

        CostoComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoComputadoraActionPerformed(evt);
            }
        });

        jLabel2.setText("Accesorios:");

        cImpresora.setText("Impresora");

        cScanner.setText("Scanner");

        cEstabilizador.setText("Estabilizador");

        jLabel3.setText("Forma de pago:");

        jLabel4.setText("Número de Cuotas:");

        credito.setText("Crédito");
        credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoActionPerformed(evt);
            }
        });

        contado.setText("Contado");
        contado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contadoActionPerformed(evt);
            }
        });

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        doce.setText("12");
        doce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doceActionPerformed(evt);
            }
        });

        dieciocho.setText("18");
        dieciocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieciochoActionPerformed(evt);
            }
        });

        Calcular.setText("CALCULAR");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        jButton2.setText("LIMPIAR");

        jButton3.setText("CERRAR");

        jLabel5.setText("Costo Total:");

        CostoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostoTotalActionPerformed(evt);
            }
        });

        jLabel6.setText("Impuesto IGV:");

        ImpuestoIGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpuestoIGVActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio a Pagar:");

        PrecioPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioPagarActionPerformed(evt);
            }
        });

        jLabel8.setText("Monto de la Cuota:");

        MontoCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MontoCuotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cImpresora)
                                .addGap(83, 83, 83)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cScanner)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cEstabilizador)
                                .addGap(20, 20, 20))
                            .addComponent(CostoComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(credito)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(contado)))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seis)
                                .addGap(10, 10, 10)
                                .addComponent(doce)
                                .addGap(10, 10, 10)
                                .addComponent(dieciocho)
                                .addContainerGap(54, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Calcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ImpuestoIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(MontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(37, 37, 37)
                                        .addComponent(PrecioPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CostoComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cImpresora)
                    .addComponent(cScanner)
                    .addComponent(cEstabilizador))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credito)
                    .addComponent(contado)
                    .addComponent(seis)
                    .addComponent(doce)
                    .addComponent(dieciocho))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Calcular)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CostoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ImpuestoIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PrecioPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(MontoCuota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CostoComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoComputadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoComputadoraActionPerformed

    private void CostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostoTotalActionPerformed

    private void ImpuestoIGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpuestoIGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImpuestoIGVActionPerformed

    private void PrecioPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioPagarActionPerformed

    private void MontoCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MontoCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MontoCuotaActionPerformed

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        boolean checkImpresora;
        boolean checkScanner;
        boolean checkEstabilizador;
        boolean checkCredito;
        boolean checkContado;
        boolean checkSeis;
        boolean checkDoce;
        boolean checkDieciocho;
        
        Double valorAccesorios;
        Double costoCompu;
        Double costoTotal;
        Double total;
        Double IGV;
        Double pagar;
        Double cuotas;
        
        valorAccesorios = 0.00;
        costoTotal = 0.00;
        total = 0.00;
        IGV = 0.00;
        pagar = 0.00;
        cuotas = 0.00;
        costoCompu = Double.parseDouble(CostoComputadora.getText());
        
        //checbox accesorios
        checkImpresora = cImpresora.isSelected();
        checkScanner = cScanner.isSelected();
        checkEstabilizador = cEstabilizador.isSelected();
        
        //checkbox forma de pago
        checkCredito = credito.isSelected();
        checkContado = contado.isSelected();
        
        //checkbox número de cuotas
        checkSeis = seis.isSelected();
        checkDoce = doce.isSelected();
        checkDieciocho = dieciocho.isSelected();
        
        if(checkImpresora){
            valorAccesorios = valorAccesorios + 240;
        }
        
        if(checkScanner){
            valorAccesorios = valorAccesorios + 80;
        }
        
        if(checkEstabilizador){
            valorAccesorios = valorAccesorios + 150;
        }
        
        //evalua credito o contado
        if(checkContado){
            costoTotal = costoCompu - 0.06*costoCompu; 
        }else{
            if(checkSeis){
                costoTotal = costoCompu + 0.05*costoCompu;
                valorAccesorios = valorAccesorios + 0.05*valorAccesorios;
                cuotas = ((costoTotal + valorAccesorios)+ 0.19*(costoTotal + valorAccesorios))/6;
            }else if(checkDoce){
                costoTotal = costoCompu + 0.06*costoCompu;
                valorAccesorios = valorAccesorios + 0.06*valorAccesorios;
                cuotas = ((costoTotal + valorAccesorios)+ 0.19*(costoTotal + valorAccesorios))/12;
            }else if(checkDieciocho){
                costoTotal = costoCompu + 0.07*costoCompu;
                valorAccesorios = valorAccesorios + 0.07*valorAccesorios;
                cuotas = ((costoTotal + valorAccesorios)+ 0.19*(costoTotal + valorAccesorios))/18;
            }
        }
        
        total = valorAccesorios + costoTotal;
        IGV = 0.19*total;
        pagar = total + IGV;
        
        CostoTotal.setText(String.valueOf(total));
        ImpuestoIGV.setText(String.valueOf(IGV));
        PrecioPagar.setText(String.valueOf(pagar));
        MontoCuota.setText(String.valueOf(cuotas));
    }//GEN-LAST:event_CalcularActionPerformed

    private void creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoActionPerformed
        // TODO add your handling code here:
        if(contado.isSelected()){
            contado.setSelected(false);
            
        }else{
            credito.setSelected(true);
            
        }
    }//GEN-LAST:event_creditoActionPerformed

    private void contadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contadoActionPerformed
        // TODO add your handling code here:
        if(credito.isSelected()){
            credito.setSelected(false);
            
        }else{
            contado.setSelected(true);
            
        }
    }//GEN-LAST:event_contadoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        if(doce.isSelected()){
            doce.setSelected(false);
        }else if(dieciocho.isSelected()){
            dieciocho.setSelected(false);
        }else{
            seis.setSelected(true);
        }
    }//GEN-LAST:event_seisActionPerformed

    private void doceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doceActionPerformed
        // TODO add your handling code here:
        if(seis.isSelected()){
            seis.setSelected(false);
        }else if(dieciocho.isSelected()){
            dieciocho.setSelected(false);
        }else{
            doce.setSelected(true);
        }
    }//GEN-LAST:event_doceActionPerformed

    private void dieciochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieciochoActionPerformed
        // TODO add your handling code here:
        if(seis.isSelected()){
            seis.setSelected(false);
        }else if(doce.isSelected()){
            doce.setSelected(false);
        }else{
            dieciocho.setSelected(true);
        }
    }//GEN-LAST:event_dieciochoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField CostoComputadora;
    private javax.swing.JTextField CostoTotal;
    private javax.swing.JTextField ImpuestoIGV;
    private javax.swing.JTextField MontoCuota;
    private javax.swing.JTextField PrecioPagar;
    private javax.swing.JCheckBox cEstabilizador;
    private javax.swing.JCheckBox cImpresora;
    private javax.swing.JCheckBox cScanner;
    private javax.swing.JRadioButton contado;
    private javax.swing.JRadioButton credito;
    private javax.swing.JRadioButton dieciocho;
    private javax.swing.JRadioButton doce;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton seis;
    // End of variables declaration//GEN-END:variables
}
